### ISSUE TITLE
Fix heroku deployment

### ISSUE THREAD

**Issue by RyanBard** [healthbam/healthbam#78]
Heroku isn't doing to so great at the GitHub integration anymore.  We can make this a travis-ci step instead:

https://docs.travis-ci.com/user/deployment/heroku
http://stackoverflow.com/questions/10235026/how-to-deploy-an-rails-app-on-heroku-from-travis-ci
https://blog.travis-ci.com/2013-07-09-introducing-continuous-deployment-to-heroku/

```
deploy:
  provider: heroku
  app:
    master: hmhb
  api_key:
    secure: <filled in by "travis encrypt $(heroku auth:token) --add deploy.api_key">
```

This doesn't seem to be what we want.

If I understand this correctly.  (after putting that in the after_succes) Creating a PR will deploy to heroku, but instead we want this to happen on PR merge.

I will work on fixing the current bridge between github and heroku instead of pursuing a Travis CI solution.
